name: Mirror to Azure DevOps

on:
  push:
    branches: ["**"]
  delete:
    branches: ["**"]
  create:
    branches: ["**"]
  workflow_dispatch:

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout full history
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Push --mirror to Azure DevOps (HTTPS + PAT)
        env:
          AZDO_PAT: ${{ secrets.AZDO_PAT }}
        run: |
          set -euo pipefail
          AZDO_ORG="AvanquestSPG"
          AZDO_PROJECT="Avanquest"
          AZDO_REPO="bolt-test-project"

          git config --global user.email "mirror-bot@avanquest.com"
          git config --global user.name  "GitHub → Azure DevOps Mirror"

          DEST_URL="https://dev.azure.com/${AZDO_ORG}/${AZDO_PROJECT}/_git/${AZDO_REPO}"
          AUTH_HEADER=$(printf ":${AZDO_PAT}" | base64 | tr -d '\n')

          # Backfill & keep in sync (all refs)
          git -c http.extraheader="AUTHORIZATION: Basic ${AUTH_HEADER}" \
              push --prune --mirror "${DEST_URL}"
